### ISSUE TITLE
Help: How to save layer as transparent PNG?

### ISSUE THREAD

**Issue by klootas** [manju-summoner/PsdParser#2]
Very nice work on this library 👍

Your test creates bitmap files out of the layers, could I ask how you would go about saving a (transparent) PNG file instead?
I managed to convert a BMP MemoryStream to save as a PNG, but the transparency is lost in the saved PNG file...

Thanks!

**Comment by manju-summoner** [comment]
I have modified the code to save in PNG format.
Please try this code.

https://github.com/manju-summoner/PsdParser/blob/ab02e501c4d09a94793a3ed654e507bacbd1e8fe/PsdParser.Test/PsdFileTest.cs#L59-L66

**Comment by klootas** [comment]
Perfect, much appreciated 👌
